import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer/footer'
// import Topnavbar from '../components/Topnavbar/Topnavbar'
import Eventbutton from '../components/Eventbutton/Eventbutton'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Unify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      
      <Eventbutton/>
        {/* <Topnavbar/>
         */}
        I Blickfånget

        <Footer/>
      </main>

    </div>
  )
}
